spring.application.name=reading-notes
spring.config.import=optional:file:./.env

spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# server
server.forward-headers-strategy=framework
server.address=0.0.0.0
server.port=${SERVER_PORT}

# front
frontend.url=${FRONTEND_URL}

# jwt
jwt.secret=${JWT_SECRET}

# logging
#logging.level.root=INFO
#logging.level.me.dodo.readingnotes=DEBUG

spring.profiles.group.prod=oauth,supabase,book,prod-only
spring.profiles.group.dev=oauth,supabase,book,dev-only

# log
# How many seconds should we log slow requests? (1000=1second)
api.log.slow-threshold-ms=1000
api.log.success-enabled=${API_LOG_SUCCESS_ENABLED:false}
auth.log.success-enabled:${AUTH_LOG_SUCCESS_ENABLED:false}