# ========================
# Kakao Book Search API
# ========================
external.kakao.book.rest-api-key=${EXTERNAL_KAKAO_BOOK_REST_API_KEY}
external.kakao.book.base-url=https://dapi.kakao.com/v3/search/book

# ========================
# National Library of Korea Open API
# ========================
external.nlk.book.cert-key=${EXTERNAL_NLK_BOOK_CERT_KEY}
external.nlk.book.base-url=https://www.nl.go.kr/seoji/SearchApi.do